#!/usr/bin/env python
from subprocess import *
import sys


def valOrExit(args):
    t = Popen(args, stdout=PIPE)
    ret = t.wait()
    if ret != 0:
        sys.exit(ret)
    return t.stdout.read().strip()

def statval(args):
    t = Popen(args, stdout=PIPE)
    ret = t.wait()
    return ret, t.stdout.read().strip()

def config(name):
    ret, val = statval(["git", "config", "--get-all", name])
    if ret != 0:
        return None
    return val

def doStatus(localBranch, remoteBranch):
    """Based on stat_tracking_info from remote.c of the git distribution"""
    #print "Comparing our %s to %s's %s" % (localBranch, remote, remoteBranch)
    # TODO: This might hang if there are so many revs that the pipe fills up.
    #       Replace with a straight call to Popen and read lines from the pipe
    #       ourselves.
    r, v = statval(["git", "rev-list", "--left-right", "%s...%s" % (localBranch, remoteBranch), "--"])
    if r != 0:
        #print "  Failed: %i" % r
        return
    ours = 0
    theirs = 0
    for line in v.split():
        if line[0] == ">":
            theirs += 1
        elif line[0] == "<":
            ours += 1
        else:
            raise Exception("Unexpected line '%s'" % line)
    if ours and not theirs:
        print "You are ahead of '%s' by %i commits" % (remoteBranch, ours)
    elif theirs and not ours:
        print "You are behind '%s' by %i commits" % (remoteBranch, theirs)
    elif ours and theirs:
        print "You have diverged from '%s'. Ahead %i, behind %i" % (remoteBranch, ours, theirs)
    else:
        print "No difference to '%s'" % (remoteBranch)

def main():
    branch = valOrExit(["git", "symbolic-ref", "HEAD"])
    #print "Branch is",branch
    if not branch.startswith("refs/heads/"):
        print "Not a local head"
        sys.exit(1)
    branch = branch[11:]
    print "Branch is", branch
    remote = config("branch.%s.remote" % branch)
    merge = config("branch.%s.merge" % branch)
    watch = config("branch.%s.watch" % branch)
    other = config("branch.%s.other" % branch)
    #print "Remote",remote
    #print "Merge",merge
    #print "Watch",watch
    if remote and merge:
        for m in merge.split():
            if not m.startswith("refs/heads/"):
                print "confused by '%s', skipping" % m
                continue
            m = m[11:]
            # TODO: How do we know that the merge branch is stored in
            #    refs/remotes/${remote}/${merge##refs/heads/}
            # ? How does git resolve this?
            doStatus(branch, "%s/%s" % (remote, m))
    if watch:
        for w in watch.split():
            doStatus(branch, w)




if __name__ == "__main__":
    main()
